# -*- coding: utf-8 -*-
"""50_tweetten_olusan_db_ile _altın_std.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jipSj4qpv_uW2EOsPZDXS6Rb1bHsAnu4
"""

import pandas as pd

# Veri setini yükle
csv_path = "/content/drive/My Drive/tweets.csv"
df = pd.read_csv(csv_path)

# Rastgele 50 örnek seç
sample_df = df.sample(n=50, random_state=42).reset_index(drop=True)

# Yeni bir sütun oluştur (manuel duygu tahminleri için)
sample_df['sentiment'] = ""

# Her bir tweeti ekrana yazdır ve kullanıcıdan etiket al
for idx, row in sample_df.iterrows():
    print(f"Tweet {idx+1}/50: {row['text']}")
    print("Duygu etiketini giriniz (Pozitif, Negatif, Nötr):")

    # Geçerli bir etiket girilene kadar döngü devam eder
    while True:
        label = input("Etiket: ").strip().capitalize()
        if label in ["Pozitif", "Negatif", "Nötr"]:
            sample_df.at[idx, 'sentiment'] = label
            break
        else:
            print("Geçersiz etiket! Lütfen 'Pozitif', 'Negatif' veya 'Nötr' giriniz.")

# Etiketlenmiş 50 tweeti yeni bir CSV dosyasına kaydet
output_file = "/content/drive/My Drive/random_50_labeled_tweets.csv"
sample_df.to_csv(output_file, index=False)

print(f"Seçilen 50 tweet etiketlendi ve dosya kaydedildi: {output_file}")

!git clone https://github.com/ViralLab/TurkishBERTweet.git

!pip install urlextract

from google.colab import drive
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from peft import PeftModel, PeftConfig
from sklearn.metrics import accuracy_score
import sys
sys.path.append('/content/TurkishBERTweet')
from Preprocessor import preprocess  # preprocess fonksiyonunu içe aktar

# Google Drive'ı bağla
drive.mount('/content/drive')

# GPU kontrolü ve ayarı
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Kullanılan cihaz:", device)

# Lora adaptör modeli ve yapılandırma
peft_model = "VRLLab/TurkishBERTweet-Lora-SA"
peft_config = PeftConfig.from_pretrained(peft_model)

# Tokenizer yükleme
tokenizer = AutoTokenizer.from_pretrained(peft_config.base_model_name_or_path)
if getattr(tokenizer, "pad_token_id") is None:
    tokenizer.pad_token_id = tokenizer.eos_token_id

# Sınıflar için etiket eşleştirmesi
id2label_sa = {0: "Negatif", 2: "Pozitif", 1: "Nötr"}
label2id_sa = {v: k for k, v in id2label_sa.items()}

# Modeli yükleme ve GPU'ya taşıma
model = AutoModelForSequenceClassification.from_pretrained(
    peft_config.base_model_name_or_path, return_dict=True, num_labels=len(id2label_sa), id2label=id2label_sa
)
model = PeftModel.from_pretrained(model, peft_model)
model.to(device)

# Manuel etiketlenmiş veri setini yükle
csv_path = "/content/drive/MyDrive/random_50_labeled_tweets.csv"  # Manuel etiketlenen veri seti
df = pd.read_csv(csv_path)

# Tweetleri temizle ve NaN değerlerini boş string ile değiştir
df['text'] = df['text'].fillna("")  # NaN değerleri boş string ile değiştir

# Her bir tweeti ön işlemden geçir
df['preprocessed_text'] = df['text'].apply(lambda tweet: preprocess(str(tweet)))

# Tahminler için toplu işlem ayarı
batch_size = 32
predictions = []

# Tahmin işlemi
for i in range(0, len(df), batch_size):
    batch_tweets = df['preprocessed_text'][i:i + batch_size].tolist()
    # Tokenizasyon
    inputs = tokenizer(
        batch_tweets,
        padding=True,
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}

    # Model ile tahmin yap
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
        batch_predictions = torch.argmax(logits, dim=-1).cpu().numpy().tolist()
        predictions.extend(batch_predictions)

# Tahminleri sınıf etiketlerine çevir
df['prediction'] = predictions
df['prediction_label'] = df['prediction'].apply(lambda x: id2label_sa[x])

# Modelin doğruluğunu hesapla
df['manual_label_id'] = df['sentiment'].apply(lambda x: label2id_sa.get(x, -1))
accuracy = accuracy_score(df['manual_label_id'], df['prediction'])

print(f"Model doğruluğu: {accuracy:.2%}")

# Sonuçları kaydet
output_file = "/content/drive/My Drive/model_vs_altın_std_comparison.csv"
df.to_csv(output_file, index=False)

print(f"Analiz tamamlandı ve sonuçlar kaydedildi: {output_file}")

