# -*- coding: utf-8 -*-
"""akoksal_bounti_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLvdZicKYJq1EjDSrK8OcaNykVl4bdEw
"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import pandas as pd
import re

# CSV dosyasını yükle
df = pd.read_csv("/content/drive/MyDrive/tweets.csv")

# Metin temizleme fonksiyonu
def clean_text(text):
    text = re.sub(r"http\S+", "", text)  # URL'leri kaldır
    text = re.sub(r"@\w+", "", text)  # Mention'ları kaldır
    text = re.sub(r"#\w+", "", text)  # Hashtag'leri kaldır
    text = re.sub(r"[^a-zA-ZğüşıöçĞÜŞİÖÇ\s]", "", text)  # Özel karakterleri kaldır
    text = text.lower()  # Küçük harfe çevir
    return text.strip()

# Metinleri temizleme
df['text'] = df['text'].astype(str).apply(clean_text)

# Model ve tokenizer'ı yükle
model_name = "akoksal/bounti"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name).to('cuda')  # GPU'ya taşı

# Sentiment tahmini fonksiyonu
def predict_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512).to('cuda')
    outputs = model(**inputs)
    probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)
    sentiment = torch.argmax(probabilities).item()
    labels = ["positive", "neutral", "negative"]
    return labels[sentiment]

# Her tweet için etiket oluştur
print("Tweetlerin etiketlenmesi başlıyor...")
df['sentiment'] = df['text'].apply(predict_sentiment)

# Etiketlenmiş CSV'yi Google Drive'a kaydet
output_file = "/content/drive/My Drive/akoksal_bounti_preprocessing.csv"
df.to_csv(output_file, index=False)
print(f"Etiketleme tamamlandı. Yeni dosya Drive'a kaydedildi: {output_file}")

# Etiket dağılımını incele
import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(data=df, x='sentiment')
plt.title("Etiket Dağılımı (Preprocessing Uygulandı)")
plt.show()

