# -*- coding: utf-8 -*-
"""anilguven_bert_tr_turkish_tweet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uFsnHY4_Xl6Mq-yawKR5HeKGG1BJzBZ2
"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

# CSV dosyasını yükle
df = pd.read_csv("/content/drive/My Drive/tweets.csv")



# TurkishBert modelii yükle
model_name = "anilguven/bert_tr_turkish_tweet"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name).to('cpu')  # GPU'ya taşıyın

# Sentiment tahmini fonksiyonu
def predict_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512).to('cuda')  # Veriyi GPU'ya taşıyın
    outputs = model(**inputs)
    probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)
    sentiment = torch.argmax(probabilities).item()
    # 0: angry, 1: afraid, 2: happy, 3: surprised, 4: sad
    if sentiment == 0:
        return "angry"
    elif sentiment == 1:
        return "afraid"
    elif sentiment == 2:
        return "happy"
    elif sentiment == 3:
        return "surprised"
    elif sentiment == 4:
        return "sad"

import torch
# Tweetleri temizle ve NaN değerlerini boş string ile değiştir
df['text'] = df['text'].fillna("")  # NaN değerleri boş string ile değiştir

# Cihaz kontrolü: GPU mevcutsa "cuda", yoksa "cpu" kullanılır
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Modeli uygun cihaza taşıma
model = model.to(device)



# Her tweet için etiket oluştur
print("Tweetlerin etiketlenmesi başlıyor...")
df['sentiment'] = df['text'].apply(predict_sentiment)

# Etiketlenmiş CSV'yi kaydet
output_file = "/content/drive/My Drive/anilguven_bert_tr_turkish_tweet_labeled.csv"
df.to_csv(output_file, index=False)
print(f"Etiketleme tamamlandı. Yeni dosya: {output_file}")

# Etiketlenmiş dosyayı indirme
from google.colab import files
files.download(output_file)

import seaborn as sns
import matplotlib.pyplot as plt

# Etiket dağılımını incele
sns.countplot(data=df, x='sentiment')
plt.title("Etiket Dağılımı")
plt.show()

