# -*- coding: utf-8 -*-
"""tum_modeller_bircsv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dh2woFzly2xGYzxpZxGAgAPy5pIJa0fe
"""

import pandas as pd

# CSV dosyalarını yükle
VRLLab_TurkishBERTweet = pd.read_csv('/content/drive/MyDrive/VRLLab_analyzed_tweets.csv')  # Türkçe model sonuçları
savasy_bert_base_turkish_sentiment_cased = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/savasy_bert-base-turkish-sentiment-cased_labeled.csv')  # İngilizce model 1 sonuçları
akoksal_bounti = pd.read_csv('/content/drive/MyDrive/akoksal_bounti_preprocessing.csv')  # İngilizce model 2 sonuçları
anilguven_bert_tr_turkish_tweet = pd.read_csv('/content/drive/MyDrive/anilguven_bert_tr_turkish_tweet_labeled.csv')  # 5 duyu model sonuçları

# Tweet bazında birleştirme yap
# 'Tweet' sütununun adı tüm dosyalarda aynı olmalı
birlesmis_df = pd.merge(VRLLab_TurkishBERTweet[['text', 'prediction_label']], savasy_bert_base_turkish_sentiment_cased[['text', 'sentiment']], on='text', suffixes=('_VRLLab_TurkishBERTweet', '_savasy_bert_base_turkish_sentiment_cased'))
birlesmis_df = pd.merge(birlesmis_df, akoksal_bounti[['text', 'sentiment']], on='text', suffixes=('', '_akoksal_bounti'))
birlesmis_df = pd.merge(birlesmis_df, anilguven_bert_tr_turkish_tweet[['text', 'sentiment']], on='text', suffixes=('', '_anilguven_bert_tr_turkish_tweet'))

# Sadece sentiment sütunlarını tutarak isimlendirme yap
birlesmis_df.rename(columns={
    'Model_Sentiment_VRLLab_TurkishBERTweet': 'VRLLab_TurkishBERTweet',
    'Model_Sentiment_savasy_bert_base_turkish_sentiment_cased': 'savasy_bert_base_turkish_sentiment_cased',
    'Model_Sentiment_akoksal_bounti': 'akoksal_bounti',
    'Model_Sentiment_anilguven_bert_tr_turkish_tweet': 'anilguven_bert_tr_turkish_tweet'
}, inplace=True)

# Sonuçları CSV'ye kaydet
birlesmis_df.to_csv('/content/drive/MyDrive/tum_modeller_bir_csvde.csv', index=False)

print("Kıyaslama dosyası oluşturuldu: tum_modeller_bir_csvde.csv")

